sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_5288b85c8e66_key -iv $encrypted_5288b85c8e66_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
install:
- chmod 600 ~/.ssh/id_rsa
# - eval `ssh-agent -s`
- ssh-add ~/.ssh/id_rsa
- git clone git@github.com:superboyiii/NEO-TEST.git ./ci2/neo-test
- cd ./ci2/neo-test/
- git checkout integration
- cd ../../
- docker build -f ci2/consensus-container/Dockerfile -t consensus .
- docker build -f ci2/ordinary-container/Dockerfile -t ordinary .
- docker network create --driver bridge --subnet=172.18.12.0/16 --gateway=172.18.1.1 neonet
jobs:
  include:
  - stage: Build-Stage
    name: build docker image
    script: echo "Finish Build Image"
  - stage: Test-Stage
    name: cli test normal
    script:
    - docker run -d --name cns --network=neonet --ip 172.18.12.1 consensus
    - docker run --name cli_test --network=neonet --ip 172.18.12.2 ordinary ./run_test.sh test_cli normal
  - script:
    - docker run -d --name cns --network=neonet --ip 172.18.12.1 consensus
    - docker run --name cli_test --network=neonet --ip 172.18.12.2 ordinary ./run_test.sh test_cli abnormal
    name: cli test abnormal
  - script:
    - docker run -d --name cns --network=neonet --ip 172.18.12.1 consensus
    - docker run --name rpc_test --network=neonet --ip 172.18.12.2 ordinary ./run_test.sh test_rpc normal
    name: rpc test normal
  - script:
    - docker run -d --name cns --network=neonet --ip 172.18.12.1 consensus
    - docker run --name rpc_test --network=neonet --ip 172.18.12.2 ordinary ./run_test.sh test_rpc abnormal
    name: rpc test abnormal

